### ISSUE TITLE
UI Mockup

### ISSUE THREAD

**Issue by jparksecurity** [teammeteoroid/overmind#7]
UI is a significant factor for the game. Let's have UI mockups here so that we have space for collaboration. 

Can you share the kakao oven link?

**Comment by hatdoc** [comment]
https://ovenapp.io/view/jnWwsBlw4imCZZ0KZGLqDHZelkKO0WPI/

**Comment by jparksecurity** [comment]
I think [this okky article](https://okky.kr/article/661646) can help us a lot. Especially, consider using [Invision ](https://www.invisionapp.com/) or [Zeplin](https://zeplin.io/) instead Kakao oven. Or you can do more research on which tool would work best for us.

We keep using the kakao oven just because the person who proposed this project used it. We never thought about what tool to use before. I think it's a good time for a change if need.

**Comment by hatdoc** [comment]
로그인
1. 처음 방문 유저에 대해선 sign up-> guest 연결 가능
2. 이미 방문한 유저는 바로 시작화면
3. 톱니: credit, 관리자 모드

새로운화면
1. 시즌선택 or 멀티 플레이어 등 선택할수 있는 화면

게임하기
1. 팀 로고& 클릭시 정보 & 맵 추가
2. 선수 클릭시 스텟 표시
3. game start 클릭시 쳇로그 있는 화면 추가

**Comment by hatdoc** [comment]
최대한 빨리 UX 를 짜고 다른 사용자에게 보여주기 위해서 그냥 kakao oven 을 써서 빨리 해결하기로 했다
